language: java

sudo: required

services:
  - docker
  -
networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450

script:
  - docker-compose -f .stack/docker/docker-compose.yml up  --build --force-recreate
  - mvn clean test