version: '3'

services:
  application:
    build:
      context: ./app
      dockerfile: Dockerfile
    network_mode: bridge
    stdin_open: true
    restart: always
    ports:
      - "8080:8080"

  selenoid:
    network_mode: bridge
    image: aerokube/selenoid:latest-release
    container_name: "selenoid"
    links:
      - application
    volumes:
      - "./selenoid/config/:/etc/selenoid/"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "$PWD/selenoid/video:/opt/selenoid/video"
      - "$PWD/selenoid/logs:/opt/selenoid/logs"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=$PWD/selenoid/video
    command: [ "-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video",
               "-log-output-dir", "/opt/selenoid/logs" ]
    ports:
      - "4444:4444"

  selenoid-ui:
    image: aerokube/selenoid-ui
    container_name: "selenoid-ui"
    network_mode: bridge
    links:
      - selenoid
    ports:
      - "8181:8181"
    command: --selenoid-uri http://selenoid:4444 --listen 0.0.0.0:8181

#  firefox_82.0:
#    image: "selenoid/vnc:firefox_82.0"
#    container_name: firefox_82.0
#    links:
#      - selenoid
#      - selenoid-ui
#    depends_on:
#      - selenoid
#      - selenoid-ui
#    networks:
#      - selenoid
#    volumes:
#      - "/dev/shm:/dev/shm"
#
#  chrome_86.0:
#    image: "selenoid/vnc:chrome_86.0"
#    container_name: chrome_86.0
#    links:
#      - selenoid
#      - selenoid-ui
#    depends_on:
#      - selenoid
#      - selenoid-ui
#    networks:
#      - selenoid
#    volumes:
#      - "/dev/shm:/dev/shm"
#
#  opera_72.0:
#    image: "selenoid/vnc:opera_72.0"
#    container_name: opera_72.0
#    links:
#      - selenoid
#      - selenoid-ui
#    depends_on:
#      - selenoid
#      - selenoid-ui
#    networks:
#      - selenoid
#    volumes:
#      - "/dev/shm:/dev/shm"
#
#  MicrosoftEdge_88.0:
#    image: "browsers/edge:88.0"
#    container_name: edge_88.0
#    links:
#      - selenoid
#      - selenoid-ui
#    depends_on:
#      - selenoid
#      - selenoid-ui
#    networks:
#      - selenoid
#    volumes:
#      - "/dev/shm:/dev/shm"
#
#  safari_13.0:
#    image: "browsers/safari:13.0"
#    container_name: safari_13.0
#    links:
#      - selenoid
#      - selenoid-ui
#    depends_on:
#      - selenoid
#      - selenoid-ui
#    networks:
#      - selenoid
#    volumes:
#      - "/dev/shm:/dev/shm"
#
#networks:
#  selenoid:
#    external:
#      name: selenoid
